Fixed the inability to descrease in size both the name and URI during escrow_update
metaplex-foundation/mpl-hybrid pull request #8
Opened 2024-10-15 10:43 UTC by tonyboylehub

During `escrow_update` there were a bunch of `check_sub()` that were causing `numericalOverflow` errors when trying to decrease the length of both `name` and `uri`

```rust
if let Some(name) = ix.name {
        size_diff += name
            .len()
            .checked_sub(escrow.name.len())
            .ok_or(MplHybridError::NumericalOverflow)? as isize;
        escrow.name = name;
    }
```

Due to `size_diff` being an isize I assumed this was supposed to enter negative numbers (and would make sense) but `checked_sub()` does not allow this.

Adjusting as follows allows the `size_dif` to enter negative values
```rust
if let Some(name) = ix.name {
        size_diff += name.len() as isize - escrow.name.len() as isize;
        escrow.name = name;
    }
```

Which in turn allows `new_size` to be calculated correctly for account size adjustment

```rust
let new_size: isize = escrow.to_account_info().data_len() as isize + size_diff;

    resize_or_reallocate_account_raw(
        &escrow.to_account_info(),
        authority,
        &ctx.accounts.system_program,
        new_size as usize,
    )?;
 ```
 
 Some `msg!()` logs from testing
![image](https://github.com/user-attachments/assets/413d2784-b17f-4ab0-b620-2626a064e1f6)
![image](https://github.com/user-attachments/assets/48fe7c7f-ee5f-4057-980c-d2ed77eefc38)

 
 Also added some update escrow tests that were missing.

### Considerations

Currently this does allow someone to set the name as nothing (0 bytes). If that's an issue we could add back an assert to the `ix.name` to check it's length is greater than 0, unless we want to set a minimun name length of 3 or something.

2024-10-29 15:07 UTC, blockiosaurus commented on programs/mpl-hybrid/src/instructions/update_escrow.rs
> +        size_diff += name.len() as isize - escrow.name.len() as isize;
I think the original checked calls should work fine if we cast to isize first (which I mistakenly did not do). Checked operations should only cause an issue if it underflows or overflows, not if it crosses zero (unless it's a usize).

2024-10-29 15:07 UTC, blockiosaurus requested changes
I'd like to keep the checked calls but adding the casting first should fix those.

2024-11-07 15:04 UTC, tonyboylehub commented on programs/mpl-hybrid/src/instructions/update_escrow.rs
> +        size_diff += name.len() as isize - escrow.name.len() as isize;
Will change that back and run tests to confirm.

2024-11-18 21:18 UTC, blockiosaurus approved these changes

2024-11-19 17:30 UTC, merged